sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
env:
  - CXX=g++-4.8
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.10"
    - node_js: "0.12"
